ALTER TABLE work_units 
ADD COLUMN monitor BOOLEAN DEFAULT FALSE,
ADD COLUMN evaluate BOOLEAN DEFAULT FALSE,
ADD COLUMN assess_or_address BOOLEAN DEFAULT FALSE,
ADD COLUMN treat BOOLEAN DEFAULT FALSE;
